targets:
  $default:
    # sources で「ビルド対象とするパス」を絞り込み、同時に不要なパスを除外することで
    # 全体のビルド時間を短縮する。
    sources:
      # 取り込みたいパス
      include:
        - lib/model/**
        - lib/redux/action/**
      # 除外したいパス
      exclude:
        - test/**         # テストコードはビルド対象から除外

    builders:
      source_gen|combining_builder:
        # このビルダーを適用したいパス
        generate_for:
          - lib/model/**
          - lib/redux/action/**
        options:
          # 入力ファイル: 生成ファイルの出力先
          build_extensions:
            '^lib/model/{{}}.dart': 'lib/model/generate/{{}}.g.dart'
            '^lib/redux/action/{{}}.dart': 'lib/redux/action/generate/{{}}.g.dart'

      freezed:
        # このビルダーを適用したいパス
        generate_for:
          - lib/model/**
          - lib/redux/action/**
        options:
          # 入力ファイル: 生成ファイルの出力先
          build_extensions:
            '^lib/model/{{}}.dart': 'lib/model/generate/{{}}.freezed.dart'
            '^lib/redux/action/{{}}.dart': 'lib/redux/action/generate/{{}}.freezed.dart'
