targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/model/todo/{{}}.dart': 'lib/model/generate/{{}}.g.dart'
      freezed:
        options:
          build_extensions:
            '^lib/model/todo/{{}}.dart': 'lib/model/generate/{{}}.freezed.dart'
            